package com.example.ui

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

enum class AppLanguage(val code: String, val displayName: String, val isRtl: Boolean) {
    ENGLISH("en", "English", false),
    ARABIC("ar", "العربية", true),
    FRENCH("fr", "Français", false),
    SPANISH("es", "Español", false),
    PORTUGUESE("pt", "Português", false),
    HINDI("hi", "हिन्दी", false),
    GERMAN("de", "Deutsch", false)
}

object LanguageHelper {
    private val translations = mapOf(
        "en" to mapOf(
            "app_title" to "FOCUS MATE AI",
            "welcome_desc" to "A premium, offline-first AI alignment experience. Speak with customized, thinking-optimized Spartan, Mentor, and Partner coaching personas to transcend daily friction.",
            "get_started" to "GET STARTED",
            "sync_session" to "SYNCHRONIZE SESSION",
            "sandbox_mode" to "Secure Offline Mode",
            "live_mode" to "Connecting to Secure Cloud Sync",
            "full_name" to "Your Full Name",
            "email_addr" to "Email Address",
            "password" to "Password",
            "init_access" to "INITIALIZE ACCESS",
            "sync_secure" to "SYNCHRONIZE SECURE",
            "or" to "OR",
            "continue_google" to "CONTINUE WITH GOOGLE",
            "google_simulator" to "GOOGLE AUTHENTICATION",
            "google_sim_desc" to "Authorize access using your Google Account credentials for secure synchronization.",
            "auth_instantly" to "SIGN IN",
            "cancel" to "CANCEL",
            "new_to_app" to "New to Focus Mate AI? Create Account",
            "already_aligned" to "Already aligned? Sign In",
            "logs_tab" to "Logs",
            "core_tab" to "Core",
            "system_tab" to "System",
            "profile" to "Profile",
            "leaderboard" to "Leaderboard",
            "settings" to "Settings",
            "night_mode" to "Night Mode",
            "language" to "App Language",
            "logout" to "Log Out",
            "upgrade" to "Upgrade to Premium",
            "premium_user" to "Premium Member",
            "free_user" to "Free Tier (Coaching Restricted)",
            "xp_points" to "XP Points",
            "rank" to "Rank",
            "biometric_login" to "Biometric Passkey",
            "biometric_desc" to "Unlock your AI alignment session with fingerprint verification.",
            "verification_title" to "Account Verification",
            "verification_desc" to "Verify your account to display a custom badge on the leaderboard.",
            "verification_enabled" to "Verified Account",
            "verification_monthly" to "Verified Account (Blue Badge)",
            "verification_yearly" to "Verified Account (Gold Badge)",
            "verification_disabled" to "Unverified Account",
            "enable_biometric" to "Enable Biometric Login",
            "disable_biometric" to "Disable Biometric Login",
            "setup_biometric_success" to "Passkey configuration aligned successfully!",
            "fingerprint_scan" to "SCAN FINGERPRINT",
            "scan_to_authenticate" to "Place finger on the reader to authenticate your node",
            "points" to "pts",
            "tasks_completed" to "Tasks Completed",
            "avatars_gallery" to "Aura Avatars Gallery",
            "free_avatar" to "Free",
            "premium_avatar" to "Premium (Locked)",
            "change_avatar_success" to "Aura representation updated successfully!",
            "coaching_history" to "Coaching History",
            "no_history" to "No alignment sessions logged yet.",
            "spartan" to "Strict Spartan",
            "mentor" to "Mindful Calm",
            "partner" to "Motivating Energizer",
            "general" to "General Assistant",
            "submit" to "SUBMIT",
            "completed" to "Completed",
            "outstanding" to "Outstanding",
            "add_task" to "Add Focus Objective",
            "task_title" to "Objective Title",
            "task_desc" to "Description of Focus",
            "add" to "ADD",
            "points_earned" to "points earned!",
            "coach_greeting" to "What Can I Do for\nYou Today?",
            "coach_idle" to "Tap the glowing core or command below. Let Focus Mate AI calibrate your momentum.",
            "command_placeholder" to "Command your Coach...",
            "sync_tasks" to "Synchronize Tasks",
            "pending_sync_queue" to "pending items in sync queue",
            "task_queue_sync" to "Task Queue Synchronization",
            "task_queue_desc" to "Command tasks. Focus Mate AI scans completed items to gauge focus, momentum, and accountability metrics.",
            "add_focus_action" to "Add Focus Action",
            "details_target" to "Details / Target",
            "queue_action" to "Queue Action",
            "sync_queue_status" to "Sync Queue Status",
            "no_actions_queued" to "No action items queued. Formulate your focus.",
            "dismiss" to "Dismiss",
            "fast_coaching_prompt" to "Give me a fast-paced dose of focus alignment based on my pending queue.",
            "personas_history_title" to "PERSONAS & HISTORY",
            "personas_history_subtitle" to "Synchronize mental models. Switch coaching architecture dynamically.",
            "aligned_logs_title" to "ALIGNED LOGS",
            "aligned_logs_empty" to "Vortex log pipeline empty. Initialize dialogue with the coach.",
            "dark_mode" to "Dark Mode",
            "light_mode" to "Light Mode",
            "recurrence_daily" to "Daily",
            "recurrence_monthly" to "Monthly",
            "recurrence_yearly" to "Yearly",
            "recurrence_custom" to "Custom (Mins)",
            "recurrence_label" to "Objective Interval",
            "duration_minutes_label" to "Duration (minutes)",
            "speak_prompt" to "Speak to your Coach...",
            "live_voice_chat" to "LIVE VOICE CHAT",
            "voice_session_active" to "Voice session active"
        ),
        "ar" to mapOf(
            "app_title" to "فوكس ميت AI",
            "welcome_desc" to "تجربة متميزة للاصطفاف الذهني بالذكاء الاصطناعي دون اتصال. تحدث مع شخصيات تدريبية مخصصة ومحسنة للتفكير (السبارتي، الفيلسوف، والشريك) لتجاوز عقباتك اليومية.",
            "get_started" to "ابدأ الآن",
            "sync_session" to "مزامنة الجلسة الآمنة",
            "sandbox_mode" to "وضع جلسة آمنة ومحلية",
            "live_mode" to "جاري الاتصال بالسحابة الآمنة",
            "full_name" to "الاسم الكامل الخاص بك",
            "email_addr" to "البريد الإلكتروني",
            "password" to "كلمة المرور",
            "init_access" to "إنشاء حساب جديد",
            "sync_secure" to "تسجيل دخول آمن",
            "or" to "أو",
            "continue_google" to "المتابعة عبر غوغل",
            "google_simulator" to "تسجيل دخول غوغل الآمن",
            "google_sim_desc" to "صرح بالوصول باستخدام حساب غوغل الخاص بك للمزامنة الآمنة والمستمرة.",
            "auth_instantly" to "تسجيل الدخول",
            "cancel" to "إلغاء",
            "new_to_app" to "جديد في التطبيق؟ أنشئ حسابك",
            "already_aligned" to "لديك حساب بالفعل؟ سجل دخولك",
            "logs_tab" to "السجلات",
            "core_tab" to "النواة",
            "system_tab" to "النظام",
            "profile" to "الحساب الشخصي",
            "leaderboard" to "المتصدرون",
            "settings" to "الإعدادات",
            "night_mode" to "الوضع الليلي",
            "language" to "لغة التطبيق",
            "logout" to "تسجيل الخروج",
            "upgrade" to "الترقية للمميز",
            "premium_user" to "عضو مميز",
            "free_user" to "الخطة المجانية (التدريب محدود)",
            "xp_points" to "نقاط الخبرة",
            "rank" to "المرتبة",
            "biometric_login" to "مفتاح البصمة والـ Passkey",
            "biometric_desc" to "افتح جلسة الاصطفاف الذهني الخاصة بك باستخدام بصمة الإصبع.",
            "verification_title" to "توثيق الحساب",
            "verification_desc" to "قم بتوثيق حسابك لعرض شارة مخصصة على لوحة الصدارة.",
            "verification_enabled" to "الحساب موثق",
            "verification_monthly" to "الحساب موثق (الشارة الزرقاء)",
            "verification_yearly" to "الحساب موثق (الشارة الذهبية)",
            "verification_disabled" to "الحساب غير موثق",
            "enable_biometric" to "تفعيل الدخول بالبصمة",
            "disable_biometric" to "إيقاف الدخول بالبصمة",
            "setup_biometric_success" to "تمت محاذاة تكوين الـ Passkey بنجاح!",
            "fingerprint_scan" to "امسح البصمة الآن",
            "scan_to_authenticate" to "ضع إصبعك على المستشعر لمصادقة هويتك",
            "points" to "نقطة",
            "tasks_completed" to "المهام المكتملة",
            "avatars_gallery" to "معرض الأفاتارات والأطياف",
            "free_avatar" to "مجاني",
            "premium_avatar" to "مميز (مغلق)",
            "change_avatar_success" to "تم تحديث مظهر الطيف الخاص بك بنجاح!",
            "coaching_history" to "سجل التدريب",
            "no_history" to "لم يتم تسجيل أي جلسات اصطفاف بعد.",
            "spartan" to "المدرب الصارم",
            "mentor" to "المدرب الهادئ",
            "partner" to "المدرب المحفز",
            "general" to "محادثة عامة",
            "submit" to "إرسال",
            "completed" to "مكتمل",
            "outstanding" to "قيد الإنجاز",
            "add_task" to "إضافة هدف تركيز جديد",
            "task_title" to "عنوان الهدف",
            "task_desc" to "وصف التركيز",
            "add" to "إضافة",
            "points_earned" to "نقاط تم حصدها!",
            "coach_greeting" to "ما الذي يمكنني فعله\nمن أجلك اليوم؟",
            "coach_idle" to "اضغط على النواة المتوهجة أو اكتب أمرًا أدناه لضبط وتيرة تركيزك.",
            "command_placeholder" to "أرسل أمرًا لمدربك الشخصي...",
            "sync_tasks" to "مزامنة المهام والتركيز",
            "pending_sync_queue" to "مهام معلقة في قائمة المزامنة",
            "task_queue_sync" to "مزامنة قائمة المهام والاهداف",
            "task_queue_desc" to "تحكّم في مهامك. يقوم التطبيق بتحليل المهام المكتملة لقياس مستويات التركيز والزخم والمسؤولية.",
            "add_focus_action" to "إضافة إجراء تركيز",
            "details_target" to "التفاصيل / الهدف المراد",
            "queue_action" to "جدولة الإجراء",
            "sync_queue_status" to "حالة قائمة المزامنة",
            "no_actions_queued" to "لا توجد مهام مجدولة حاليًا. حدد أهداف تركيزك.",
            "dismiss" to "إغلاق",
            "fast_coaching_prompt" to "أعطني جرعة سريعة من توجيه التركيز بناءً على قائمتي المعلقة.",
            "personas_history_title" to "الشخصيات والسجلات",
            "personas_history_subtitle" to "مزامنة النماذج العقلية والتبديل بين أساليب التدريب ديناميكيًا.",
            "aligned_logs_title" to "السجلات والتقارير",
            "aligned_logs_empty" to "سجل التدريب فارغ حاليًا. ابدأ محادثتك الأولى مع المدرب.",
            "dark_mode" to "الوضع الليلي",
            "light_mode" to "الوضع النهاري",
            "recurrence_daily" to "يومية",
            "recurrence_monthly" to "شهرية",
            "recurrence_yearly" to "سنوية",
            "recurrence_custom" to "مخصصة بالدقائق",
            "recurrence_label" to "تكرار الهدف والمدة",
            "duration_minutes_label" to "المدة بالدقائق",
            "speak_prompt" to "تحدث الآن مع مدربك الشخصي...",
            "live_voice_chat" to "محادثة صوتية مباشرة",
            "voice_session_active" to "المحادثة الصوتية المباشرة نشطة"
        ),
        "fr" to mapOf(
            "app_title" to "FOCUS MATE AI",
            "welcome_desc" to "Une expérience d'alignement IA premium hors ligne. Échangez avec des avatars optimisés (Spartiate, Mentor, Partenaire) pour transcender les frictions du quotidien.",
            "get_started" to "COMMENCER",
            "sync_session" to "SYNCHRONISER LA SESSION",
            "sandbox_mode" to "Mode Sandbox (Alternative locale active)",
            "live_mode" to "Connexion sécurisée à Supabase Cloud",
            "full_name" to "Votre Nom Complet",
            "email_addr" to "Adresse Email",
            "password" to "Mot de passe",
            "init_access" to "INITIALISER L'ACCÈS",
            "sync_secure" to "CONNEXION SÉCURISÉE",
            "or" to "OU",
            "continue_google" to "CONTINUER AVEC GOOGLE",
            "google_simulator" to "SIMULATEUR DE CONNEXION GOOGLE",
            "google_sim_desc" to "L'API Google Sign-In est active. Contournement des registres réseau en mode sandbox.",
            "auth_instantly" to "AUTHENTIFICATION INSTANTANÉE",
            "cancel" to "ANNULER",
            "new_to_app" to "Nouveau sur Focus Mate AI ? Créer un compte",
            "already_aligned" to "Déjà aligné ? Se connecter",
            "logs_tab" to "Journaux",
            "core_tab" to "Noyau",
            "system_tab" to "Système",
            "profile" to "Profil",
            "leaderboard" to "Classement",
            "settings" to "Paramètres",
            "night_mode" to "Mode Sombre",
            "language" to "Langue de l'App",
            "logout" to "Se Déconnecter",
            "upgrade" to "Devenir Premium",
            "premium_user" to "Membre Premium",
            "free_user" to "Niveau Gratuit (Coaching Limité)",
            "xp_points" to "Points d'XP",
            "rank" to "Rang",
            "biometric_login" to "Passkey Biométrique",
            "biometric_desc" to "Déverrouillez votre session d'alignement IA avec votre empreinte digitale.",
            "enable_biometric" to "Activer la connexion biométrique",
            "disable_biometric" to "Désactiver la connexion biométrique",
            "setup_biometric_success" to "Configuration du Passkey alignée avec succès !",
            "fingerprint_scan" to "SCANNER L'EMPREINTE",
            "scan_to_authenticate" to "Placez votre doigt sur le lecteur pour authentifier votre nœud",
            "points" to "pts",
            "tasks_completed" to "Tâches Complétées",
            "avatars_gallery" to "Galerie d'Avatars",
            "free_avatar" to "Gratuit",
            "premium_avatar" to "Premium (Verrouillé)",
            "change_avatar_success" to "Représentation d'Aura mise à jour avec succès !",
            "coaching_history" to "Historique de Coaching",
            "no_history" to "Aucune session d'alignement enregistrée.",
            "spartan" to "Spartiate",
            "mentor" to "Mentor",
            "partner" to "Partenaire",
            "general" to "Assistant Général",
            "submit" to "SOUMETTRE",
            "completed" to "Terminé",
            "outstanding" to "En suspens",
            "add_task" to "Ajouter un Objectif de Focus",
            "task_title" to "Titre de l'Objectif",
            "task_desc" to "Description du Focus",
            "add" to "AJOUTER",
            "points_earned" to "points obtenus !",
            "coach_greeting" to "Que puis-je faire pour\nvous aider aujourd'hui?",
            "coach_idle" to "Appuyez sur le noyau lumineux ou écrivez une commande ci-dessous. Laissez Focus Mate AI calibrer votre élan.",
            "command_placeholder" to "Commandez votre Coach...",
            "sync_tasks" to "Synchroniser les Tâches",
            "pending_sync_queue" to "éléments en attente dans la file de synchro",
            "task_queue_sync" to "Synchronisation de la File des Tâches",
            "task_queue_desc" to "Gérez vos tâches. Focus Mate AI analyse les éléments complétés pour évaluer votre concentration, élan et rigueur.",
            "add_focus_action" to "Ajouter une Action Focus",
            "details_target" to "Détails / Objectif",
            "queue_action" to "Planifier l'Action",
            "sync_queue_status" to "Statut de la File de Synchro",
            "no_actions_queued" to "Aucune tâche planifiée. Formulez vos objectifs de focus.",
            "dismiss" to "Fermer",
            "fast_coaching_prompt" to "Donnez-moi une dose rapide d'alignement de focus basée sur mes tâches en attente.",
            "personas_history_title" to "PERSONNALITÉS & HISTORIQUE",
            "personas_history_subtitle" to "Synchronisez vos modèles mentaux. Changez de coach dynamiquement.",
            "aligned_logs_title" to "JOURNAUX D'ALIGNEMENT",
            "aligned_logs_empty" to "File d'attente des journaux vide. Initialisez le dialogue avec le coach."
        ),
        "es" to mapOf(
            "app_title" to "FOCUS MATE AI",
            "welcome_desc" to "Una experiencia de alineación con IA de primer nivel y sin conexión. Habla con coaches optimizados (Espartano, Mentor, Compañero) para trascender la fricción diaria.",
            "get_started" to "COMENZAR",
            "sync_session" to "SINCRO DE SESIÓN",
            "sandbox_mode" to "Modo Sandbox (Alternativa local activa)",
            "live_mode" to "Conectando de forma segura a Supabase Cloud",
            "full_name" to "Nombre Completo",
            "email_addr" to "Correo Electrónico",
            "password" to "Contraseña",
            "init_access" to "INICIALIZAR ACCESO",
            "sync_secure" to "SINCRO SECURA",
            "or" to "O",
            "continue_google" to "CONTINUAR CON GOOGLE",
            "google_simulator" to "SIMULADOR DE GOOGLE SIGN-IN",
            "google_sim_desc" to "La API de Google Sign-In está activa. Evitando registros de red en modo sandbox.",
            "auth_instantly" to "AUTENTICAR AL INSTANTE",
            "cancel" to "CANCELAR",
            "new_to_app" to "¿Nuevo en Focus Mate AI? Crear Cuenta",
            "already_aligned" to "¿Ya estás alineado? Iniciar Sesión",
            "logs_tab" to "Registros",
            "core_tab" to "Núcleo",
            "system_tab" to "Sistema",
            "profile" to "Perfil",
            "leaderboard" to "Clasificación",
            "settings" to "Ajustes",
            "night_mode" to "Modo Oscuro",
            "language" to "Idioma de la App",
            "logout" to "Cerrar Sesión",
            "upgrade" to "Mejorar a Premium",
            "premium_user" to "Miembro Premium",
            "free_user" to "Plan Gratuito (Coaching Limitado)",
            "xp_points" to "Puntos XP",
            "rank" to "Rango",
            "biometric_login" to "Passkey Biométrica",
            "biometric_desc" to "Desbloquea tu sesión de alineación con tu huella dactilar.",
            "enable_biometric" to "Activar inicio biométrico",
            "disable_biometric" to "Desactivar inicio biométrico",
            "setup_biometric_success" to "¡Configuración de Passkey alineada con éxito!",
            "fingerprint_scan" to "ESCANEAR HUELLA",
            "scan_to_authenticate" to "Coloque el dedo en el lector para autenticar su nodo",
            "points" to "pts",
            "tasks_completed" to "Tareas Completadas",
            "avatars_gallery" to "Galería de Avatares",
            "free_avatar" to "Gratis",
            "premium_avatar" to "Premium (Bloqueado)",
            "change_avatar_success" to "¡Representación de Aura actualizada con éxito!",
            "coaching_history" to "Historial de Coaching",
            "no_history" to "No hay sesiones de alineación registradas.",
            "spartan" to "Espartano",
            "mentor" to "Mentor",
            "partner" to "Compañero",
            "general" to "Asistente General",
            "submit" to "ENVIAR",
            "completed" to "Completado",
            "outstanding" to "Pendiente",
            "add_task" to "Añadir Objetivo de Enfoque",
            "task_title" to "Título del Objetivo",
            "task_desc" to "Descripción del Enfoque",
            "add" to "AÑADIR",
            "points_earned" to "puntos ganados!",
            "coach_greeting" to "¿Qué puedo hacer por\nti hoy?",
            "coach_idle" to "Toca el núcleo brillante o escribe un comando abajo. Deja que Focus Mate AI calibre tu impulso.",
            "command_placeholder" to "Ordena a tu Coach...",
            "sync_tasks" to "Sincronizar Tareas",
            "pending_sync_queue" to "tareas pendientes en la cola de sincronización",
            "task_queue_sync" to "Sincronización de Cola de Tareas",
            "task_queue_desc" to "Controla tus tareas. Focus Mate AI analiza los elementos completados para evaluar la concentración, el impulso y la responsabilidad.",
            "add_focus_action" to "Añadir Acción de Enfoque",
            "details_target" to "Detalles / Objetivo",
            "queue_action" to "Programar Acción",
            "sync_queue_status" to "Estado de Cola de Sincronización",
            "no_actions_queued" to "No hay tareas programadas. Formula tus objetivos.",
            "dismiss" to "Descartar",
            "fast_coaching_prompt" to "Dame una dosis rápida de alineación de enfoque basada en mis tareas pendientes.",
            "personas_history_title" to "PERSONAS E HISTORIAL",
            "personas_history_subtitle" to "Sincroniza modelos mentales. Cambia la arquitectura de coaching dinámicamente.",
            "aligned_logs_title" to "REGISTROS ALINEADOS",
            "aligned_logs_empty" to "Canal de registro de historial vacío. Inicia el diálogo con el coach."
        ),
        "pt" to mapOf(
            "app_title" to "FOCUS MATE AI",
            "welcome_desc" to "Uma experiência premium de alinhamento com IA offline. Fale com mentores otimizados (Espartano, Mentor, Parceiro) para superar a fricção diária.",
            "get_started" to "COMEÇAR",
            "sync_session" to "SINCRONIZAR SESSÃO",
            "sandbox_mode" to "Modo Sandbox (Alternativa local ativa)",
            "live_mode" to "Conectando com segurança ao Supabase Cloud",
            "full_name" to "Seu Nome Completo",
            "email_addr" to "Endereço de E-mail",
            "password" to "Senha",
            "init_access" to "INICIALIZAR ACESSO",
            "sync_secure" to "SINCRONIZAR SEGURO",
            "or" to "OU",
            "continue_google" to "CONTINUAR COM GOOGLE",
            "google_simulator" to "SIMULADOR DE GOOGLE SIGN-IN",
            "google_sim_desc" to "A API Google Sign-In está ativa. Ignorando registros de rede no modo sandbox.",
            "auth_instantly" to "AUTENTICAR INSTANTANEAMENTE",
            "cancel" to "CANCELAR",
            "new_to_app" to "Novo no Focus Mate AI? Criar Conta",
            "already_aligned" to "Já está alinhado? Entrar",
            "logs_tab" to "Registros",
            "core_tab" to "Núcleo",
            "system_tab" to "Sistema",
            "profile" to "Perfil",
            "leaderboard" to "Classificação",
            "settings" to "Configurações",
            "night_mode" to "Modo Escuro",
            "language" to "Idioma do App",
            "logout" to "Sair da Conta",
            "upgrade" to "Upgrade para Premium",
            "premium_user" to "Membro Premium",
            "free_user" to "Nível Gratuito (Coaching Restrito)",
            "xp_points" to "Pontos de XP",
            "rank" to "Rank",
            "biometric_login" to "Passkey Biométrica",
            "biometric_desc" to "Desbloqueie sua sessão de alinhamento com IA usando sua digital.",
            "enable_biometric" to "Ativar login biométrico",
            "disable_biometric" to "Desativar login biométrico",
            "setup_biometric_success" to "Configuração do Passkey alinhada com sucesso!",
            "fingerprint_scan" to "ESCANEAR DIGITAL",
            "scan_to_authenticate" to "Coloque o dedo no leitor para autenticar o seu nó",
            "points" to "pts",
            "tasks_completed" to "Tarefas Completadas",
            "avatars_gallery" to "Galeria de Avatares Aura",
            "free_avatar" to "Grátis",
            "premium_avatar" to "Premium (Bloqueado)",
            "change_avatar_success" to "Representação de Aura atualizada com sucesso!",
            "coaching_history" to "Histórico de Coaching",
            "no_history" to "Nenhum alinhamento registrado ainda.",
            "spartan" to "Espartano",
            "mentor" to "Mentor",
            "partner" to "Parceiro",
            "general" to "Assistente Geral",
            "submit" to "ENVIAR",
            "completed" to "Concluído",
            "outstanding" to "Pendente",
            "add_task" to "Adicionar Objetivo de Foco",
            "task_title" to "Título do Objetivo",
            "task_desc" to "Descrição do Foco",
            "add" to "ADICIONAR",
            "points_earned" to "pontos ganhos!",
            "coach_greeting" to "O que posso fazer por\nvocê hoje?",
            "coach_idle" to "Toque no núcleo brilhante ou digite um comando abaixo. Deixe o Focus Mate AI calibrar seu impulso.",
            "command_placeholder" to "Comande seu Treinador...",
            "sync_tasks" to "Sincronizar Tarefas",
            "pending_sync_queue" to "tarefas pendentes na fila de sincronização",
            "task_queue_sync" to "Sincronização da Fila de Tarefas",
            "task_queue_desc" to "Gerencie suas tarefas. O Focus Mate AI analisa os itens concluídos para avaliar o foco, impulso e métricas de responsabilidade.",
            "add_focus_action" to "Adicionar Ação de Foco",
            "details_target" to "Detalhes / Objetivo",
            "queue_action" to "Agendar Ação",
            "sync_queue_status" to "Status da Fila de Sincronização",
            "no_actions_queued" to "Nenhuma tarefa agendada. Formule seus objetivos.",
            "dismiss" to "Fechar",
            "fast_coaching_prompt" to "Dê-me uma dose rápida de alinhamento de foco com base na minha fila pendente.",
            "personas_history_title" to "PERSONAS E HISTÓRICO",
            "personas_history_subtitle" to "Sincronize modelos mentais. Alterne a arquitetura de coaching dinamicamente.",
            "aligned_logs_title" to "REGISTROS ALINHADOS",
            "aligned_logs_empty" to "Fila de registros vazia. Inicie o diálogo com o treinador."
        ),
        "hi" to mapOf(
            "app_title" to "FOCUS MATE AI",
            "welcome_desc" to "एक प्रीमियम, ऑफ़लाइन-प्रथम एआई संरेखण अनुभव। दैनिक घर्षण को पार करने के लिए अनुकूलित स्पार्टन, मेंटर और पार्टनर कोचिंग व्यक्तित्वों के साथ बात करें।",
            "get_started" to "शुरू करें",
            "sync_session" to "सत्र सिंक्रनाइज़ करें",
            "sandbox_mode" to "सैंडबॉक्स मोड (स्थानीय ऑफ़लाइन फ़ॉलबैक सक्रिय)",
            "live_mode" to "सुपाबेस क्लाउड से सुरक्षित रूप से कनेक्ट किया जा रहा है",
            "full_name" to "आपका पूरा नाम",
            "email_addr" to "ईमेल पता",
            "password" to "पासवर्ड",
            "init_access" to "एक्सेस आरंभ करें",
            "sync_secure" to "सुरक्षित सिंक",
            "or" to "अथवा",
            "continue_google" to "गूगल के साथ जारी रखें",
            "google_simulator" to "गूगल साइन-इन सिम्युलेटर",
            "google_sim_desc" to "गूगल साइन-इन एपीआई सक्रिय है। सैंडबॉक्स मोड में नेटवर्क रजिस्ट्रियों को बायपास किया जा रहा है।",
            "auth_instantly" to "तुरंत प्रमाणित करें",
            "cancel" to "रद्द करें",
            "new_to_app" to "फोकस मेट एआई में नए हैं? खाता बनाएं",
            "already_aligned" to "पहले से जुड़े हैं? साइन इन करें",
            "logs_tab" to "लॉग्स",
            "core_tab" to "कोर",
            "system_tab" to "सिस्टम",
            "profile" to "प्रोफ़ाइल",
            "leaderboard" to "लीडरबोर्ड",
            "settings" to "सेटिंग्स",
            "night_mode" to "डार्क मोड",
            "language" to "ऐप की भाषा",
            "logout" to "लॉग आउट करें",
            "upgrade" to "प्रीमियम में अपग्रेड करें",
            "premium_user" to "प्रीमियम सदस्य",
            "free_user" to "फ्री टियर (कोचिंग प्रतिबंधित)",
            "xp_points" to "एक्सपी पॉइंट्स",
            "rank" to "रैंक",
            "biometric_login" to "बायोमेट्रिक पास-की",
            "biometric_desc" to "फिंगरप्रिंट सत्यापन के साथ अपने एआई संरेखण सत्र को अनलॉक करें।",
            "enable_biometric" to "बायोमेट्रिक लॉगिन सक्षम करें",
            "disable_biometric" to "बायोमेट्रिक लॉगिन अक्षम करें",
            "setup_biometric_success" to "पासकी कॉन्फ़िगरेशन सफलतापूर्वक संरेखित किया गया!",
            "fingerprint_scan" to "फिंगरप्रिंट स्कैन करें",
            "scan_to_authenticate" to "अपने नोड को प्रमाणित करने के लिए रीडर पर उंगली रखें",
            "points" to "अंक",
            "tasks_completed" to "पूरे किए गए कार्य",
            "avatars_gallery" to "ऑरा अवतार गैलरी",
            "free_avatar" to "मुफ़्त",
            "premium_avatar" to "प्रीमियम (लॉक)",
            "change_avatar_success" to "ऑरा प्रतिनिधित्व सफलतापूर्वक अपडेट किया गया!",
            "coaching_history" to "कोचिंग इतिहास",
            "no_history" to "अभी तक कोई संरेखण सत्र लॉग नहीं किया गया है।",
            "spartan" to "स्पार्टन",
            "mentor" to "मेंटर",
            "partner" to "पार्टनर",
            "general" to "सामान्य सहायक",
            "submit" to "जमा करें",
            "completed" to "पूरा हुआ",
            "outstanding" to "अपूर्ण",
            "add_task" to "फोकस उद्देश्य जोड़ें",
            "task_title" to "उद्देश्य शीर्षक",
            "task_desc" to "फोकस का विवरण",
            "add" to "जोड़ें",
            "points_earned" to "अंक अर्जित किए गए!",
            "coach_greeting" to "आज मैं आपके लिए\nक्या कर सकता हूँ?",
            "coach_idle" to "चमकते हुए कोर पर टैप करें या नीचे कमांड लिखें। फोकस मेट एआई को अपनी गति को जांचने दें।",
            "command_placeholder" to "अपने कोच को निर्देश दें...",
            "sync_tasks" to "कार्यों को सिंक करें",
            "pending_sync_queue" to "सिंक कतार में लंबित कार्य",
            "task_queue_sync" to "कार्य कतार सिंक्रनाइज़ेशन",
            "task_queue_desc" to "कार्यों को नियंत्रित करें। फोकस मेट एआई एकाग्रता, गति और जवाबदेही मेट्रिक्स को मापने के लिए पूर्ण किए गए कार्यों को स्कैन करता है।",
            "add_focus_action" to "फोकस एक्शन जोड़ें",
            "details_target" to "विवरण / लक्ष्य",
            "queue_action" to "एक्शन कतार में लगाएं",
            "sync_queue_status" to "सिंक कतार स्थिति",
            "no_actions_queued" to "कोई एक्शन कतारबद्ध नहीं है। अपने फोकस को तैयार करें।",
            "dismiss" to "खारिज करें",
            "fast_coaching_prompt" to "मुझे मेरी लंबित कतार के आधार पर फोकस संरेखण की त्वरित सलाह दें।",
            "personas_history_title" to "व्यक्तित्व और इतिहास",
            "personas_history_subtitle" to "मानसिक मॉडलों को सिंक्रनाइज़ करें। कोचिंग आर्किटेक्चर को गतिशील रूप से बदलें।",
            "aligned_logs_title" to "संरेखित लॉग्स",
            "aligned_logs_empty" to "इतिहास लॉग खाली है। कोच के साथ संवाद शुरू करें।"
        ),
        "de" to mapOf(
            "app_title" to "FOCUS MATE AI",
            "welcome_desc" to "Ein erstklassiges, offline-erstes KI-Ausrichtungserlebnis. Sprechen Sie mit maßgeschneiderten, denkoptimierten Spartan-, Mentor- und Partner-Coaching-Personas.",
            "get_started" to "LOSLEGEN",
            "sync_session" to "SITZUNG SYNCHRONISIEREN",
            "sandbox_mode" to "Sandbox-Modus (Lokaler Offline-Fallback aktiv)",
            "live_mode" to "Sichere Verbindung zur Supabase Cloud",
            "full_name" to "Ihr vollständiger Name",
            "email_addr" to "E-Mail-Adresse",
            "password" to "Passwort",
            "init_access" to "ZUGANG INITIALISIEREN",
            "sync_secure" to "SICHER SYNCHRONISIEREN",
            "or" to "ODER",
            "continue_google" to "MIT GOOGLE FORTFAHREN",
            "google_simulator" to "GOOGLE SIGN-IN SIMULATOR",
            "google_sim_desc" to "Google Sign-In API ist aktiv. Netzwerkregistrierungen im Sandbox-Modus umgehen.",
            "auth_instantly" to "SOFORT AUTHENTIFIZIEREN",
            "cancel" to "ABBRECHEN",
            "new_to_app" to "Neu bei Focus Mate AI? Konto erstellen",
            "already_aligned" to "Bereits registriert? Einloggen",
            "logs_tab" to "Protokolle",
            "core_tab" to "Kern",
            "system_tab" to "System",
            "profile" to "Profil",
            "leaderboard" to "Rangliste",
            "settings" to "Einstellungen",
            "night_mode" to "Nachtmodus",
            "language" to "App-Sprache",
            "logout" to "Abmelden",
            "upgrade" to "Auf Premium upgraden",
            "premium_user" to "Premium-Mitglied",
            "free_user" to "Kostenlose Stufe (Coaching eingeschränkt)",
            "xp_points" to "XP-Punkte",
            "rank" to "Rang",
            "biometric_login" to "Biometrischer Passkey",
            "biometric_desc" to "Entsperren Sie Ihre KI-Ausrichtungssitzung per Fingerabdruck.",
            "enable_biometric" to "Biometrisches Login aktivieren",
            "disable_biometric" to "Biometrisches Login deaktivieren",
            "setup_biometric_success" to "Passkey-Konfiguration erfolgreich ausgerichtet!",
            "fingerprint_scan" to "FINGERABDRUCK SCANNEN",
            "scan_to_authenticate" to "Legen Sie Ihren Finger auf den Scanner, um Ihren Knoten zu authentifizieren",
            "points" to "Pkt.",
            "tasks_completed" to "Abgeschlossene Aufgaben",
            "avatars_gallery" to "Aura-Avatar-Galerie",
            "free_avatar" to "Kostenlos",
            "premium_avatar" to "Premium (Gesperrt)",
            "change_avatar_success" to "Aura-Darstellung erfolgreich aktualisiert!",
            "coaching_history" to "Coaching-Verlauf",
            "no_history" to "Noch keine Sitzungen protokolliert.",
            "spartan" to "Spartaner",
            "mentor" to "Mentor",
            "partner" to "Partner",
            "general" to "Allgemeiner Assistent",
            "submit" to "ABSENDEN",
            "completed" to "Abgeschlossen",
            "outstanding" to "Ausstehend",
            "add_task" to "Fokus-Ziel hinzufügen",
            "task_title" to "Titel des Ziels",
            "task_desc" to "Beschreibung des Fokus",
            "add" to "HINZUFÜGEN",
            "points_earned" to "Punkte gesammelt!",
            "coach_greeting" to "Was kann ich heute für\ndich tun?",
            "coach_idle" to "Tippe auf den leuchtenden Kern oder gib unten einen Befehl ein. Lass Focus Mate AI deinen Schwung kalibrieren.",
            "command_placeholder" to "Befehle deinem Coach...",
            "sync_tasks" to "Aufgaben synchronisieren",
            "pending_sync_queue" to "ausstehende Elemente in der Synch-Warteschlange",
            "task_queue_sync" to "Aufgaben-Synchronisation",
            "task_queue_desc" to "Steuere deine Aufgaben. Focus Mate AI scannt erledigte Elemente, um Fokus, Dynamik und Verantwortlichkeitsmetriken zu messen.",
            "add_focus_action" to "Fokus-Aktion hinzufügen",
            "details_target" to "Details / Ziel",
            "queue_action" to "Aktion einplanen",
            "sync_queue_status" to "Synch-Warteschlangen-Status",
            "no_actions_queued" to "Keine Aktionen in der Warteschlange. Formuliere deinen Fokus.",
            "dismiss" to "Schließen",
            "fast_coaching_prompt" to "Gib mir eine schnelle Dosis Fokus-Ausrichtung basierend auf meiner Warteschlange.",
            "personas_history_title" to "PERSONAS & VERLAUF",
            "personas_history_subtitle" to "Synchronisiere mentale Modelle. Wechsle das Coaching-Modell dynamisch.",
            "aligned_logs_title" to "SYNCHRONISIERTE PROTOKOLLE",
            "aligned_logs_empty" to "Protokoll-Pipeline leer. Beginne ein Gespräch mit dem Coach."
        )
    )

    private val _currentLanguage = MutableStateFlow(AppLanguage.ENGLISH)
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage

    fun setLanguage(language: AppLanguage) {
        _currentLanguage.value = language
    }

    fun translate(key: String, lang: String = _currentLanguage.value.code): String {
        if (key == "app_title") {
            val customName = com.example.Config.getAppNameWithoutContext()
            if (!customName.isNullOrBlank()) {
                return customName
            }
        }
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
